# Generated by Django 4.2.3 on 2023-09-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_basicnote_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicnote',
            name='color',
            field=models.CharField(default='FFF700', max_length=7),
        ),
    ]
