# Generated by Django 4.2.3 on 2023-10-01 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0005_alter_basicnote_checkmark_alter_basicnote_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleblock',
            name='week',
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basicnote',
            name='color',
            field=models.CharField(default='#f39c12', max_length=7),
        ),
        migrations.DeleteModel(
            name='WeekSchedule',
        ),
    ]
