# Generated by Django 4.2.3 on 2023-10-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_remove_scheduleblock_week_scheduleblock_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleblock',
            name='color',
            field=models.CharField(default='#f39c12', max_length=7),
        ),
        migrations.AlterField(
            model_name='scheduleblock',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='scheduleblock',
            name='endTime',
            field=models.TimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='scheduleblock',
            name='startTime',
            field=models.TimeField(verbose_name='Start Time'),
        ),
    ]
