# Generated by Django 4.2.3 on 2023-10-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_scheduleblock_color_alter_scheduleblock_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleblock',
            name='endTime',
            field=models.TimeField(blank=True, null=True, verbose_name='End Time'),
        ),
    ]
