# Generated by Django 4.2.3 on 2023-10-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_alter_basicnote_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicnote',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Description'),
        ),
    ]
