# Generated by Django 4.2.3 on 2023-10-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_alter_basicnote_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicnote',
            name='until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
